//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentas
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public int Porcentaje_Descuento { get; set; }
        public int Porcentaje_Incrmento { get; set; }
        public double Subtotal { get; set; }
        public Nullable<int> Producto_Id { get; set; }
        public Nullable<int> Ventas_Id { get; set; }
        public Nullable<double> PrecioProd { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
