//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devoluciones
    {
        public int Id_devolucion { get; set; }
        public int Id_pedido { get; set; }
        public string Motivos { get; set; }
        public int status { get; set; }
        public string observaciones { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
