//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos_provedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos_provedores()
        {
            this.Pedidos_Productos = new HashSet<Pedidos_Productos>();
        }
    
        public int Id_pedido_prov { get; set; }
        public int Id_proveedor { get; set; }
        public System.DateTime fecha { get; set; }
        public int autorizacion { get; set; }
        public Nullable<double> saldo_restante { get; set; }
        public int pago { get; set; }
        public Nullable<double> Total { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fechaautoriza { get; set; }
        public string razon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos_Productos> Pedidos_Productos { get; set; }
        public virtual Provedores Provedores { get; set; }
    }
}
